### ISSUE TITLE
Unable to set header using let variable containing text ${aaa.yyyy}

### ISSUE THREAD

**Issue by subhashreddy98** [smartrics/RestFixture#118]
I have a header value which is captured using let like below 
| let | loginSessionId | header | Set-Cookie:(.+) | |
which results in output as below.
|let|loginSessionId|header	|Set-Cookie:(.+)
|JSESSIONID="5D9A85ABEBFA96ACF903C24EC42C3F5C.${aaa.yyy}"; Version=1; Path=/yyy

When I use this variable to setHeader 
|setHeader|Set-Cookie:%loginSessionId%|
Below exception is coming. 
I expect the header value to be set as, in this case like below 
Set-Cookie:5D9A85ABEBFA96ACF903C24EC42C3F5C.${aaa.yyy}"; Version=1; Path=/yyy

java.lang.RuntimeException: Method named setHeader threw an exception when executing.
    at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:834)
    at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1151)
    at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:362)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:16)
    at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:44)
    at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:31)
    at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:53)
    at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
    at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:123)
    at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:101)
    at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
    at fitnesse.slim.instructions.Instruction.execute(Instruction.java:30)
    at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
    at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
    at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83)
    at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:87)
    at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:80)
    at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:59)
    at fitnesse.slim.SlimServer.serve(SlimServer.java:45)
    at fitnesse.slim.SlimService.handle(SlimService.java:184)
    at fitnesse.slim.SlimService.acceptOne(SlimService.java:192)
    at fitnesse.slim.SlimService.accept(SlimService.java:154)
    at fitnesse.slim.SlimService.startWithFactory(SlimService.java:75)
    at fitnesse.slim.SlimService.main(SlimService.java:56)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:818)
    ... 27 more
Caused by: java.lang.IllegalArgumentException: named capturing group is missing trailing '}'
    at java.util.regex.Matcher.appendReplacement(Matcher.java:792)
    at java.util.regex.Matcher.replaceAll(Matcher.java:906)
    at java.lang.String.replaceAll(String.java:2162)
    at smartrics.rest.fitnesse.fixture.support.Variables.substitute(Variables.java:125)
    at smartrics.rest.fitnesse.fixture.RestFixture.setHeader(RestFixture.java:506)
    ... 32 more

**Comment by smartrics** [comment]
Hi - the problem is that the header value isn't escaped. I will fix on next version of RestFixture.
for now, can you try if this workaroud works for you?

|let      | loginSessionId | header |Set-Cookie:(.+) | |
|let      | loginSessionId2 | js | symbols.get('loginSessionId').replace('{', '\\{') | |
|setHeader| Set-Cookie:%loginSessionId2% | |

**Comment by subhashreddy98** [comment]
Thank you that works.

**Comment by smartrics** [comment]
fix available on RestFixture 4.1
