### ISSUE TITLE
Let method not working in smartrics-RestFixture-4.0

### ISSUE THREAD

**Issue by NibhaSanghai** [smartrics/RestFixture#123]
Hi,

When I try to execute the following using smartrics-RestFixture-4.0, i get the following error, while the same works fine with smartrics-RestFixture-3.0
Error:
382 [main] ERROR smartrics.rest.fitnesse.fixture.RestFixture - Exception raised when processing row let
java.lang.RuntimeException: Method named let threw an exception when executing.
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:862)
	at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1185)
	at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:16)
	at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:43)
	at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:30)
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:52)
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:121)
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:99)
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:30)
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:50)
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:44)
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:84)
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:106)
	at fitnesse.slim.SlimServer.processTheInstructions(SlimServer.java:93)
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:68)
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:54)
	at fitnesse.slim.SlimServer.serve(SlimServer.java:40)
	at fitnesse.slim.SlimService.handle(SlimService.java:164)
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:172)
	at fitnesse.slim.SlimService.accept(SlimService.java:134)
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:65)
	at fitnesse.slim.SlimService.main(SlimService.java:51)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:846)
	... 28 more
Caused by: java.lang.NoSuchMethodError: fitnesse.slim.StatementExecutorInterface.assign(Ljava/lang/String;Ljava/lang/Object;)V
	at smartrics.rest.fitnesse.fixture.support.SlimVariables.put(SlimVariables.java:54)
	at smartrics.rest.fitnesse.fixture.RestFixture.let(RestFixture.java:759)
	... 33 more

FitNesse Page:
!define TEST_SYSTEM {slim}

!path C:/automation/Fitnesse/smartrics-RestFixture-4.0/lib/*
!path C:/automation/Fitnesse/smartrics-RestFixture-4.0/lib/smartrics-RestFixture-4.0.jar
!path C:/automation/Fitnesse/smartrics-RestFixture-3.0/lib/slf4j-simple-1.6.6.jar

!define http {http:/}

|Table:smartrics.rest.fitnesse.fixture.RestFixture |${http}/abc.xyz.com|
|setBody| {dummy body} |
|setHeader|Content-Type: application/json|
|POST| <url> | 200 | | |
|let|length|header|Content-Length:(.+) ||

**Comment by smartrics** [comment]
Hello I am not able to reproduce it. Chen what version of fitnesse you are using because RestFixture 4.0 is compatible with http://mvnrepository.com/artifact/org.fitnesse/fitnesse/20150424 or above

**Comment by NibhaSanghai** [comment]
Ok. Would try the same.

**Comment by NibhaSanghai** [comment]
It works fine with new version of FitNesse. Thanks
