### ISSUE TITLE
Json assertion failing with IlegalArgumentException for arrays

### ISSUE THREAD

**Issue by subhashreddy98** [smartrics/RestFixture#126]
Hello,
I'm facing an issue while asserting json fields. If the field doesn't exist in json "not found" error is thrown but when an not existing array is referred IllegalArgumentException: Cannot evaluate exception is thrown.
Can you please improve this to throw "not found" error instead of exception.

Example:
when below json is test output, assertion happens fine
{"name":"test post","data":"some data","array":[{"id":"some data"}]}
when below json is test output, assertion fails without cannot evaluation exception. 
{"name":"test post","data":"some data"}

!-jsonbody.name=='test post' && jsonbody.data=='some data' && jsonbody.array[0].id=='some data' -!

java.lang.IllegalArgumentException: Cannot evaluate 'jsonbody.array[0].id=='some data'' in {  "name": "test post",  "data": "some data"}
    at smartrics.rest.fitnesse.fixture.support.XPathBodyTypeAdapter.equals(XPathBodyTypeAdapter.java:77)
    at smartrics.rest.fitnesse.fixture.support.JSONBodyTypeAdapter.equals(JSONBodyTypeAdapter.java:74)
    at smartrics.rest.fitnesse.fixture.RestFixture.process(RestFixture.java:1008)
    at smartrics.rest.fitnesse.fixture.RestFixture.completeHttpMethodExecution(RestFixture.java:969)
    at smartrics.rest.fitnesse.fixture.RestFixture.doMethod(RestFixture.java:895)
    at smartrics.rest.fitnesse.fixture.RestFixture.PUT(RestFixture.java:537)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:818)
    at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1151)
    at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:362)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:80)
    at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:44)
    at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:31)
    at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:57)
    at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
    at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:126)
    at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:104)
    at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
    at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
    at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
    at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
    at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83)
    at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:84)
    at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:77)
    at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:56)
    at fitnesse.slim.SlimServer.serve(SlimServer.java:42)
    at fitnesse.slim.SlimService.handle(SlimService.java:186)
    at fitnesse.slim.SlimService.acceptOne(SlimService.java:194)
    at fitnesse.slim.SlimService.accept(SlimService.java:156)
    at fitnesse.slim.SlimService.startWithFactory(SlimService.java:77)
    at fitnesse.slim.SlimService.main(SlimService.java:57)
Caused by: smartrics.rest.fitnesse.fixture.support.JavascriptException: TypeError: Cannot read property "0.0" from undefined (unnamed script#1)
    at smartrics.rest.fitnesse.fixture.support.JavascriptWrapper.evaluateExpression(JavascriptWrapper.java:128)
    at smartrics.rest.fitnesse.fixture.support.JavascriptWrapper.evaluateExpression(JavascriptWrapper.java:97)
    at smartrics.rest.fitnesse.fixture.support.JSONBodyTypeAdapter.eval(JSONBodyTypeAdapter.java:47)
    at smartrics.rest.fitnesse.fixture.support.XPathBodyTypeAdapter.equals(XPathBodyTypeAdapter.java:72)
    ... 37 more

**Comment by subhashreddy98** [comment]
Steps to reproduce: Please add below test case in Test "smartrics.rest.fitnesse.fixture.support.JSONBodyTypeAdapterTest"

   @Test
    public void arrayNotFoundAssert(){
    	assertFalse(adapter.equals(Arrays.asList("jsonbody.d[0]=='next'"), json0));
    	assertEquals("not found: 'jsonbody.d[0]=='zzz''", adapter.getErrors().get(0));
    }

**Comment by smartrics** [comment]
Hi - the RestFixture must not interpret the expression itself and make decisions on the content.
The error that you get is a valid response given that your javascript expression is invalid when the array is not present

I suggest you change your assertion to 

jsonbody.d instanceof Array && jsonbody.d[0]=='next'

So the unit test you suggested, if appropriately modified, will pass: 

@Test
public void arrayNotFoundAssert(){
assertFalse(adapter.equals(Arrays.asList("jsonbody.d instanceof Array && jsonbody.d[0]=='next'"), json0));
}

**Comment by kirru1432000** [comment]
**Hi Smartrics,

I am facing the similar kind of problem.
my json structure is 
{
"items":[
{
"item1":"value1",
"item2":"value2",
"item3":"value3",
"item4":"value4"
}
,{..........},
{..........}
] ,
"things":{
"specialThings":[
{"A":"1"},
{"B":"2"},
{"C":"3"}
]
}
"error":null
}

I have to validate A,B,C values and Am using the xpath "//things/specialThings[0]/A[text()='1']" to assert by using rest fixture,but am getting illegal argument exception.

**Comment by DeepakDabas** [comment]
Hi,

When I am trying to assert the below response from REST API. It is giving error --ava.lang.IllegalArgumentException: Cannot evaluate '"id"' in {"id":"5" ...
The response of the URI is - 
{"id":"5","name":"ABCT","address":"G-BLOCK, SURAJPUR KASNA ROAD,6","description":"(A DIVISION OF )"}

I have created a decision table with following details

setHeader	Content-Type : application/json
setBody	jsonbody
GET	/societyDetails/5	200	Content-Type : text/html; charset=UTF-8	"id"

Please suggest

**Comment by smartrics** [comment]
"id" is not an assertion. you need to formulate an expression whose result is a true/false, like

jsonbody.id=="5"
