### ISSUE TITLE
Pass LET symbol in body that has embedded "" in the symbols

### ISSUE THREAD

**Issue by nuggit32** [smartrics/RestFixture#142]
My POST is not working because I think the %value% has some characters in the string that is making the POST fail? Am I passing the symbol correctly if the symbols contains %, /, ",?

I store some symbols like the following:

|let|www_authenticate |js|response.header0('WWW-Authenticate')||

I then add the symbol to my body like so:

  "X-Idaas-Rest-Application-Context": "-!%www_authenticate%!-",

Result looks like the following:(I also add the X-Idaas-Rest-Subject-Value as a restfixture symbol as well.

"X-Idaas-Rest-Application-Context": "OAM-Auth realm="blahGate:2 http://txxxxamapp02c:59991/oic_rest/rest/mobilejxxxxmauthentication", request-ctx="encquery%3DKlOuFcCtH23pZNMcnXCrU1d%2Bpg1ahFPhIhkWkOflo3SFVSUBTA7f1hNOL3prZt%2BImFcUZc6op3mEZjyOkKVrgj7iFzM394uU3MC%2BvOLU6C%2BlSYqbONJVGzGNXWOi0FaTHOqEeZU8XjeeEDjKgWLQ70XKHYyjcCb3Jerz37SXT5JdXXfQ5qDkvksQNpQcCV1yK7IYF%2B4uSuGurDwjK7Hbd9%2BFVM6Rp%2FS1ePFuNU9F9CYhlhgKciAYsEqBRIcI6ydHjIUp%2Bcj0S5k8m67L30vdDHh8e0lEJDZh27czZ9TJUBXVgBHHIo21Z51l%2BiLr53DJDhrPfPfcjoYq1yYl%2Bxr6Lg%3D%3D%20agentid%3DIHSWebGate%20ver%3D1%20crmethod%3D2"",

  "X-Idaas-Rest-Subject-Value": "UFCA/mA093X+nfpVwL55vVDsgcnS5H2VuOpStK1Yu75Ce6foqLieL9va8JIYduFuwHDP9OY0t1zTcXMnQ1xL46UNE4CoMRDtCX64MJnMVJHcl7VhYnhVhTV03DJEA70xhnHBt8fwMzwuatSoCHaRMTSJmKyMeKrOJnQVxpjp4pFQ1NLWgEqMBkBtQfBXvTqcAxvMZvwmLKqqavyhZw0xCJ4vlCZiC3CCntuesp3zBLZ5/ziFj8lsEXdBjnEQL8jE2NB+v8ep6DmdYTtv05P94jrvKbZgi6Ic1FSEcUaenUuHUDiKhg5BMgbi0Lp64fDPtUgI8icUMIvLKfrT5uFX0WipWtkKwqfoI1dZ2MbacsVhfa5mtqIDvOkZ0NRHeJe2ELPdnOdveVHlQUklKiVKfkfv/Sw/RUpqhJ4Hab+Y8SrM+OVKm5vsKiK/g8k/24ZK+3yYpiHLbNJqeidM+P/7ih9LwfJUHEHCqx5eeBdfnVwpYj4Xye5FUkVcAiXvoGQi",

  "X-Idaas-Rest-Application-Resource": "/RESTWeb/2.8.0/createbbbtoken"

My POST throws exception:

java.lang.RuntimeException: Method named POST threw an exception when executing.
    at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:862)
    at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1188)
    at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:390)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:81)
    at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:57)
    at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:38)
    at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:72)
    at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
    at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:126)
    at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:104)
    at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
    at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
    at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
    at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
    at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83)
    at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:87)
    at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:80)
    at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:58)
    at fitnesse.slim.SlimServer.serve(SlimServer.java:43)
    at fitnesse.slim.SlimService.handle(SlimService.java:186)
    at fitnesse.slim.SlimService.acceptOne(SlimService.java:194)
    at fitnesse.slim.SlimService.accept(SlimService.java:156)
    at fitnesse.slim.SlimService.startWithFactory(SlimService.java:77)
    at fitnesse.slim.SlimService.main(SlimService.java:57)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:846)
    ... 27 more
Caused by: java.lang.NullPointerException
    at smartrics.rest.fitnesse.fixture.support.SlimVariables.get(SlimVariables.java:64)
    at smartrics.rest.fitnesse.fixture.support.Variables.substitute(Variables.java:98)
    at smartrics.rest.fitnesse.fixture.RestFixture.doMethod(RestFixture.java:921)
    at smartrics.rest.fitnesse.fixture.RestFixture.POST(RestFixture.java:675)
    ... 32 more

**Comment by nuggit32** [comment]
So my issue is with this line in my body:

I pass it as follows:

|let|www_authenticate |js|response.header('WWW-Authenticate')||

In setbody
"X-Idaas-Rest-Application-Context": "-!%www_authenticate%!-",

The value of www_authenticate is

"X-Idaas-Rest-Application-Context": "OAM-Auth realm="IHSWebGate:2 http://txxxxxmoamapp02c:599901/oic_rest/rest/mobilexxxoamauthentication", request-ctx="encquery%3Dinz9DC7vj%2BJsDU6PRKWZS0EcgwgYr0aoK38Zg5PUEC8kLuH3tkGUklOgo0cwWnzSRQMQtbO0o2OHk9BAJzQDaVbUhCHa2faugT%2BoRvaQ0rOIQGhjU1zPyqssh%2FJbhfcTOWGtLI%2BTNVK9BB4AxSyPb5tVSLKVtLOSxuCEK1Bf2inA9Qht2huRWtZca5Mv%2FNFkfRyJQjPj%2B224g7AF4n2il%2FqYHlgeBdLNkPkrYywOcwZ1DKnVDWMea9e4sfWM8z9sFJ8FcI9lYutIVbcT0lg2Q2MfVy21MO9Fu7uysotd8sZgBJhDjJvu80sywUhdFbdA%2B9xOyzpFuOmE4qlUQ0oApw%3D%3D%20agentid%3DIHSWebGate%20ver%3D1%20crmethod%3D2"",

This causes Restfixture POST to fail.

I put the same request in POSTMAN and it works if I added \ infront of the " like the following:

"X-Idaas-Rest-Application-Context": "OAM-Auth realm=\"IHSWebGate:2 http://txxxxxmoamapp02c:599901/oic_rest/rest/mobilexxxoamauthentication\", request-ctx=\"encquery%3Dinz9DC7vj%2BJsDU6PRKWZS0EcgwgYr0aoK38Zg5PUEC8kLuH3tkGUklOgo0cwWnzSRQMQtbO0o2OHk9BAJzQDaVbUhCHa2faugT%2BoRvaQ0rOIQGhjU1zPyqssh%2FJbhfcTOWGtLI%2BTNVK9BB4AxSyPb5tVSLKVtLOSxuCEK1Bf2inA9Qht2huRWtZca5Mv%2FNFkfRyJQjPj%2B224g7AF4n2il%2FqYHlgeBdLNkPkrYywOcwZ1DKnVDWMea9e4sfWM8z9sFJ8FcI9lYutIVbcT0lg2Q2MfVy21MO9Fu7uysotd8sZgBJhDjJvu80sywUhdFbdA%2B9xOyzpFuOmE4qlUQ0oApw%3D%3D%20agentid%3DIHSWebGate%20ver%3D1%20crmethod%3D2\"",

I tried a hard coded version of adding the \" in restfixture but that did not fix the problem either.  

How do I handle a restfixture symbol that has embedded "" without causing the POST to fail?

**Comment by nuggit32** [comment]
so I was able to write the Javascript to modify the symbol to add the escape character "\" in the X-Idaas-Rest-Application-Context body.  However the restfixture  is still failing on the POST.  The exact same body is working in Postman.


{
  "X-Idaas-Rest-New-Token-Type-To-Create": "ACCESSTOKEN",
  "X-Idaas-Rest-Subject-Type": "TOKEN",
  "deviceProfile": {
    "oracle:idm:claims:client:ostype": "iPhone OS",
    "oracle:idm:claims:client:osversion": "8.4",
    "oracle:idm:claims:client:locale": "en_US",
    "oracle:idm:claims:client:networktype": "WIFI",
    "oracle:idm:claims:client:sdkversion": "11.1.2.2.0",
    "hardwareIds": {
      "oracle:idm:claims:client:imei": "0000000000000000",
      "oracle:idm:claims:client:udid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "oracle:idm:claims:client:phonenumber": "0-000-000-0000"
    },
    "oracle:idm:claims:client:geolocation": "0,0",
    "oracle:idm:claims:client:jailbroken": false 
  },
  "X-Idaas-Rest-Application-Context": "OAM-Auth realm=\"XXXXXXXXXX:2 http://txxxmoamxxx02c:59991/xxx_rest/rest/mobilejwtoamauthentication\", request-ctx=\"encquery%3DO9Cji0OE8YV6%2BtzQW1t%2Ffl4tn3S0yle8xRYJ%2BgWT4lXaQrivnhpV8Co88%2B%2B8kt0DuVz0JNHj3O0LgkhLRbrmW9rr5fbuZoXeFlPtLvjmDsW6tgfp%2FyUE1W6z4WJKcchn1i6cdIa%2BCy9z8NdbtvSVUadWzkzvwE8KCNxcxitavJuOKoxju%2BhK0rcn4DiccebSLBIReMsQdFNT5lJu%2BfJDXFLVuANkNE5TuJFIJ3SAuRCTla1FynH4clyesVhoUyqqu5uKJ5NZd3bYEmUyvW%2B%2FmuligSSJPofsg%2F2a4QIqOT6bHO0kT52XXerV2cEk3dqbZZVY4BM5FNYx5RmcAYRSBA%3D%3D%20agentid%3DIHSWebGate%20ver%3D1%20crmethod%3D2\"",
  "X-Idaas-Rest-Subject-Value": "Ncz9g8pk7ctJ3c7IJE0SJDtm9hAfqtlAhRgZWWLPa7gpPAkl+2TMmzJ8JqkkX0G4A2YgksgKQ82Xv5zpC/IdEUPw3LYQzLZXtoS0Vz8ELcyojiCFUYmx20CjZhVBCp8BDZgalfNPPN/4EZ5t1DbFLvPPQMzUNSTL9bkPRsmz9OB/3EUS3A9u0xywh4dA81Whj+7fRtfWGdg2avQhERcf8boSRdP+aZHF1EZF7fa7T50o9HO4u7RACs884anQVEyGL1cAVOJULXXfr412rwA51pip4I0d+o3rHRTT2A89QTqS7UEpXwEPSlFK4Gvd1J5pq6RI9Q/iK4SSkG2qaFUHp8xwWaMtwVOPY80N+KJAEIMKJjofxbcZIDeSaF1FNNbax5q1W7JIgNElHtVxIQ+DvK7CkhAAAmoaFmgGAHqF4cYofSQp+TSdhsp0HyI1q3J9l2POLYoM7NQv+71mFiJ1jrPj7e+uioq02CBSOhZoqWsB6eWaJDSv2/dtr3vRHM//",
  "X-Idaas-Rest-Application-Resource": "/RESTXXX/2.8.8/createtoken"
}

3278 [main] ERROR smartrics.rest.fitnesse.fixture.RestFixture - Exception raised when processing row POST
java.lang.RuntimeException: Method named POST threw an exception when executing.
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:862)
	at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1188)
	at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:81)
	at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:57)
	at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:38)
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:72)
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:126)
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:104)
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83)
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:87)
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:80)
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:58)
	at fitnesse.slim.SlimServer.serve(SlimServer.java:43)
	at fitnesse.slim.SlimService.handle(SlimService.java:186)
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:194)
	at fitnesse.slim.SlimService.accept(SlimService.java:156)
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:77)
	at fitnesse.slim.SlimService.main(SlimService.java:57)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:846)
	... 27 more
Caused by: java.lang.NullPointerException
	at smartrics.rest.fitnesse.fixture.support.SlimVariables.get(SlimVariables.java:64)
	at smartrics.rest.fitnesse.fixture.support.Variables.substitute(Variables.java:98)
	at smartrics.rest.fitnesse.fixture.RestFixture.doMethod(RestFixture.java:921)
	at smartrics.rest.fitnesse.fixture.RestFixture.POST(RestFixture.java:675)
	... 32 more

I'm using Restfixture 4.1 and fitnesse v20150814

**Comment by nuggit32** [comment]
My issue was that I needed to escape the " and convert the % to the The HTML Coded Character Set &#37;

Example: oam is the symbol and replacing % with &#37; and replacing " with \ infront so it has \".
|let|oam|js| String(symbols.get('oam').replace('%', '&#37;') .replace('"', "\\\"")) | |
