### ISSUE TITLE
get.symbols not working as expected

### ISSUE THREAD

**Issue by nuggit32** [smartrics/RestFixture#143]
trying to use get.symbols to retreive a symbol for javascript manipulation but appears to not work?
Code:  Simply replacing " with \" as per example in issue 118.
|let|www_authenticate |js|response.header0('WWW-Authenticate')||
|let|www2|js| symbols.get('www_authenticate').replace('"', '\"')||

Output
let www_authenticate	js	
response.header0('WWW-Authenticate')
OAM-Auth realm="IHSWebGate:2 http://tjudmoamapp02c:50991/ocd_rest/rest/mobilejbllamauthentication", request-ctx="encquery%3DEwx0vYj6Jwt6ZMds66OhJEKe%2FZADpTRrcz1HwNiAOhlEbsMtku%2BS8%2Bo201RtyY%2BqhaPMTmaFZ8imSZZTj7iNnP7%2FYhI8gMdYbmvN3vU%2FcISKLaaLHrVOypaWJy%2B8MB9lpRjBk9ojx1sHZsrRHv5lwLaRzYFcQjyBXvZhvXy4nEal0d2mVqqBctCAnADt2rhspbgxrfzKDDt5jwKpu5pY1UXPkwuFQqzSKAuEaq%2BPWCEdtKJQmtoE1jsn839d%2FsGaFnQ7qTiFWd6J054EYgKCiRsPGW0QjkvSJkViPUF7MouQ7ZAB3%2BsiysR8DWYsnz%2F6IYD8SG%2BWszGFE6YlxSTgrw%3D%3D%20agentid%3DIHSWebGate%20ver%3D1%20crmethod%3D2"

let	www2	js	
symbols.get('www_authenticate').replace('"', '\"')
org.mozilla.javascript.NativeJavaObject@1677d1

Results in org.mozilla.javascript.NativeJavaObject@1677d1 ?????

**Comment by nuggit32** [comment]
Here is a simple test that I expect to work:  I'm using 4.1 version as well.

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:9091 |
| GET | /RestFixtureInstallTest?rss | | | |
|let|x |js|response.header0('Content-Type')||
|let|y|js| symbols.get('x')||


RESULT:
Table:smartrics.rest.fitnesse.fixture.RestFixture	http://localhost:9091
GET	/RestFixtureInstallTest?rss  200
Server : FitNesse-v20150814
Connection : close
Content-Length : 128
Content-Type : text/xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rss version="2.0">
<channel>
<title>FitNesse:</title>
</channel>
</rss>
let |  x  | js  |   response.header0('Content-Type')    |     text/xml
let | y  |  js  | symbols.get('x') | org.mozilla.javascript.NativeJavaObject@60c6f5b

I expected to see that y = text/xml like X shows?

Am I wrong on my expectations?

And if I was add the symbols.get().replace method, replacing / with " the result would be text"xml?

**Comment by smartrics** [comment]
Hi I am not 100% clear on what you're trying to do with the replace() but see if this example works for you

|Table:smartrics.rest.fitnesse.fixture.RestFixture | |
|let| foo | const | "a"a" | |
|let|y|js| String(symbols.get('foo')).replace(/"/g, "\\\"")||

You need to force the symbol to a js String.

**Comment by nuggit32** [comment]
Okay I tried your example and that does not work either...It throws a stack trace.

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:9091 |
|let| foo | const | "a"a" | |
|let|y|js| String(symbols.get('foo')).replace(/"/g, "\\"")||

157 [main] ERROR smartrics.rest.fitnesse.fixture.RestFixture - Exception occurred when processing cell=smartrics.rest.fitnesse.fixture.SlimCell@3a82f6ef
smartrics.rest.fitnesse.fixture.support.JavascriptException: unterminated string literal (unnamed script#1)
	at smartrics.rest.fitnesse.fixture.support.JavascriptWrapper.evaluateExpression(JavascriptWrapper.java:133)
	at smartrics.rest.fitnesse.fixture.support.JavascriptWrapper.evaluateExpression(JavascriptWrapper.java:83)
	at smartrics.rest.fitnesse.fixture.support.LetBodyJsHandler.handle(LetBodyJsHandler.java:39)
	at smartrics.rest.fitnesse.fixture.RestFixture.let(RestFixture.java:753)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:846)
	at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1188)
	at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:81)
	at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:57)
	at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:38)
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:72)
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:126)
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:104)
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83)
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:87)
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:80)
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:58)
	at fitnesse.slim.SlimServer.serve(SlimServer.java:43)
	at fitnesse.slim.SlimService.handle(SlimService.java:186)
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:194)
	at fitnesse.slim.SlimService.accept(SlimService.java:156)
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:77)
	at fitnesse.slim.SlimService.main(SlimService.java:57)

**Comment by nuggit32** [comment]
To clarify my point on what I was trying to do.  I'm just testing to see how to replace values in symbols.
In the below example  x = text/xml, so I'm trying to replace xml with say json to make y = text/json to test the logic.

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:9091 |
| GET | /RestFixtureInstallTest?rss | | | |
|let|x |js|response.header0('Content-Type')||
|let|y|js| symbols.get('x').replace('xml', 'json') | |

When I run this test y = org.mozilla.javascript.NativeJavaObject@5ce81285,  not text/json

Appreciate anything I'm doing wrong.  Seems straight forward?

Herb

**Comment by nuggit32** [comment]
Okay I fixed my issue.....needed String().
|let|y|js| String(symbols.get('x').replace('xml', 'json')) | |
