### ISSUE TITLE
Pass Symbol that has % in the string

### ISSUE THREAD

**Issue by nuggit32** [smartrics/RestFixture#144]
I have a need to pass a token in the header for a POST request.  The problem is the token has % in the string and thus makes.

The token comes back to me in a prior Get request like so:

OAM-AUTH XAgJCDJOTv8CMeAxLjmdNEM8WT8bV%2BVul5Dd22f2nQv8XqAn3uyiv0u8IyNss9WHuQli7qzDr2NLF%2B%2Bnez4k8%2F59RSnD5pKxkXvP6S4KIPtiEZsJqz7AvObBWlnIpg%2BufnzSVqrao8fkochu5jrDNUyasTDVLXrsLJhnIM0Xo0H9D59zAr%2F%2F3UtKZRdwCRzvlv86Marqw6yt23pxJbiqCcFtGh79pX8QRImM8w200osBnT94hGnPtG5RdxBlRtQbB9rCoxn7irOvd7TBTMd%2FEK1u46CnCRQmB2e9F6AXiL9Cb651jAouDlIRo7Z7uHSFhEAMRAAi2tj6ElsBxoGHZY2ypZ5pCHu47dT%2BoPr1E4dgantKbtRt7mEC%2Bb75lasa%2BVVNgf5nH%2BXsbSDIkIlwqdcFl9mDZl7LpdE7znvtoQ6dH8Lig8g%2BkfiiensBCHFw9boUCdKyUPaizj5Cz1bB5Jv60Vc5kfCx2OpXYUaXdfn%2FqZgIxlUvjXiyY2HUMfBT

If I pass this to the POST it failes with a stacktrace:
54 [main] ERROR smartrics.rest.fitnesse.fixture.RestFixture - Exception raised when processing row setHeader
java.lang.RuntimeException: Method named setHeader threw an exception when executing.
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:862)
	at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1188)
	at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:81)
	at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:57)
	at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:38)
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:72)
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:126)
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:104)
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83)
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:87)
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:80)
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:58)
	at fitnesse.slim.SlimServer.serve(SlimServer.java:43)
	at fitnesse.slim.SlimService.handle(SlimService.java:186)
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:194)
	at fitnesse.slim.SlimService.accept(SlimService.java:156)
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:77)
	at fitnesse.slim.SlimService.main(SlimService.java:57)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:846)
	... 27 more
Caused by: java.lang.NullPointerException
	at smartrics.rest.fitnesse.fixture.support.SlimVariables.get(SlimVariables.java:64)
	at smartrics.rest.fitnesse.fixture.support.Variables.substitute(Variables.java:98)
	at smartrics.rest.fitnesse.fixture.RestFixture.setHeader(RestFixture.java:534)
	... 32 more
Nov 20, 2015 9:41:51 AM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.

I've tried to escpae the % with \%\ and that allows the request to go through.  However the token is not valid anymore as \%\ changes the values of the token so I get a 401 error code. Not Authorized.

What is the best way to pass a authorization token via the restfixture that has % in the symbols?

Appreciate anyone that has experience in this.

**Comment by nuggit32** [comment]
I'm answering my own questions :)   The way to do this is as follows for replacint / % and + symbols.
| let | token | js | String(symbols.get('oken').replace('%2B', '+') .replace('%2F', '/') .replace('%3D', '='))  |  |
