### ISSUE TITLE
Not able to run the Tests from CommandLine

### ISSUE THREAD

**Issue by samdinesh86** [smartrics/RestFixture#213]
I am not able to run the tests from the command line. 
'D:\FitNesse\scratch>java -jar target\dependencies\fitnesse-20151230.jar -c "Auth
enticate?test&format=text"
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/velocity/c
ontext/Context
        at fitnesse.FitNesseContext.<init>(FitNesseContext.java:83)
        at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.
java:125)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:65)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:54)
        at fitnesseMain.FitNesseMain.main(FitNesseMain.java:34)
Caused by: java.lang.ClassNotFoundException: org.apache.velocity.context.Context

        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more

**Comment by smartrics** [comment]
I am not sure how the classpath is formed when running from cmdline.

Are the paths to the dependency jars in your tests relative? and are they relative to the directory where you run the command?

Also, you could try and set the -cp to target\depdendencies and see if it makes any difference.

**Comment by samdinesh86** [comment]
D:\FitNesse\scratch>java -cp !CLASSPATH! fitnesseMain.FitNesseMain -c 'Authentic
ate?test  & format=text"
Loaded custom comparator inverse: fitnesse.slim.test.InverseComparator
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance test
ing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Unpacking new version of FitNesse resources. Please be patient...
**********************************************************
Files have been updated to a new version.
Please read the release notes on
http://localhost:9123/FitNesse.ReleaseNotes
to find out about the new features and fixes.
**********************************************************
Executing command: 'Authenticate?test
java.lang.Exception: error loading page: 404
        at fitnesse.FitNesse.executeSingleCommand(FitNesse.java:99)
        at fitnesseMain.FitNesseMain.executeSingleCommand(FitNesseMain.java:128)

        at fitnesseMain.FitNesseMain.launch(FitNesseMain.java:102)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:82)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:54)
        at fitnesseMain.FitNesseMain.main(FitNesseMain.java:34)
Invalid drive specification.

**Comment by smartrics** [comment]
from the error the classpath issue seems it's been fixed.
now you have a 404

"'Authenticate?test
java.lang.Exception: error loading page: 404"

It may depend on how you have arranged your fixtures in the file system.

**Comment by smartrics** [comment]
I assume you have this covered now - if not do reopen this issue.
