### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by cmaster007** [smartrics/RestFixture#246]
if i post a rest api, reponse content too long,will error:

java.lang.IllegalStateException: Http call failed for IO failure
	at smartrics.rest.client.RestClientImpl.execute(RestClientImpl.java:159)
	at smartrics.rest.client.RestClientImpl.execute(RestClientImpl.java:99)
	at smartrics.rest.fitnesse.fixture.RestFixture.doMethod(RestFixture.java:1151)
	at smartrics.rest.fitnesse.fixture.RestFixture.doMethod(RestFixture.java:1093)
	at smartrics.rest.fitnesse.fixture.RestFixture.POST(RestFixture.java:850)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at smartrics.rest.fitnesse.fixture.RestFixture.processRow(RestFixture.java:1021)
	at smartrics.rest.fitnesse.fixture.RestFixture.processSlimRow(RestFixture.java:1367)
	at smartrics.rest.fitnesse.fixture.RestFixture.doTable(RestFixture.java:432)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:147)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.callMethod(DefaultInteraction.java:132)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.invokeMethod(DefaultInteraction.java:114)
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.findAndInvoke(DefaultInteraction.java:92)
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18)
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18)
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:130)
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:103)
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85)
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82)
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75)
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62)
	at fitnesse.slim.SlimServer.serve(SlimServer.java:47)
	at fitnesse.slim.SlimService.handle(SlimService.java:168)
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:176)
	at fitnesse.slim.SlimService.accept(SlimService.java:138)
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:91)
	at fitnesse.slim.SlimService.main(SlimService.java:56)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at smartrics.rest.client.RestClientImpl.execute(RestClientImpl.java:139)
	... 37 more

**Comment by cmaster007** [comment]
who can help me ? this is must update smartics-RestClient-2.2.jar

**Comment by cmaster007** [comment]
ok，solve the problem

**Comment by smartrics** [comment]
Hi - what's the length of the response causing the issue?
